name: Email API CI Build

run-name: Build triggered by ${{ github.event_name }} & defined by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: api

jobs:
  build:
    name: 'Build project'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.18.0
        cache-dependency-path: api/yarn.lock
        cache: 'yarn'
    - name: 'Install dependencies'
      run: yarn --frozen-lockfile
    - name: 'Build project'
      run: yarn build
    - name: 'Upload artifcates to S3'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 sync dist s3://email-service-ci-build-bucket-prod/builds/${{ github.run_id }}

  notify-result:
    name: Notify result
    runs-on: ubuntu-latest

    steps:
      - name: 'Call notifications API'
        run: | 
          curl -i \
          -H "Accept: application/json" \
          -X POST -d '{"branch":"${{ github.ref_name }}","repository":"${{ github.repository }}","userName":"${{ github.actor }}","commit":{"hash":"${{ github.sha }}","message":"${{ github.event.head_commit.message }}","url":"https://github.com/${{ github.event.organization }}/${{ github.event.repository }}/commit/${{ github.sha }}"},"workflow":"${{ github.workflow }}","status":"${{ github.action_status }}"}' \
          https://eswi9rdwzc.execute-api.us-east-1.amazonaws.com/prod/notifications