name: Email API CI Build

run-name: Build triggered by ${{ github.event_name }} & defined by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    name: 'Build project'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Install dependencies'
      run: yarn --frozen-lockfile
    - name: 'Build project'
      run: yarn build
    - name: 'Upload artifcates to S3'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 sync ./dist s3://email-service-ci-build-bucket-prod/builds/${{ github.run_id }}