name: CI Build

run-name: ${{ github.event.head_commit.message }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - development

env:
  API_URL:  ${{ github.ref == 'refs/heads/main' && vars.API_URL_PROD || vars.API_URL_STG }}
  S3_BUCKET_NAME:  ${{ github.ref == 'refs/heads/main' && vars.S3_BUCKET_NAME_PROD || vars.S3_BUCKET_NAME_STG }}

jobs:
  build:
    name: "Build project"
    runs-on: ubuntu-latest

    outputs:
      duration: ${{ steps.duration_calc.outputs.duration }}

    steps:
      - name: Start timer
        id: timer_start
        run: echo "start=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache-dependency-path: api/yarn.lock
          cache: "yarn"
      
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: api
      
      - name: Build project
        run: yarn build
        working-directory: api
      
      - name: Upload artifcates to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync dist s3://${{ env.S3_BUCKET_NAME }}/builds/${{ github.run_id }}
        working-directory: api
      
      - name: Calculate duration
        id: duration_calc
        run: |
          end=$(date +%s)
          start=${{ steps.timer_start.outputs.start }}
          duration=$((end - start))
          echo "duration=$duration" >> $GITHUB_OUTPUT
          echo "Duration: $duration seconds"

  notify-result:
    name: Notify result
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !cancelled() }}

    steps:
      - name: "Call notifications API"
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -i \
          -H "Accept: application/json" \
          -X POST -d '{"branch":"${{ github.ref_name }}","repository":"${{ github.repository }}","userName":"${{ github.actor }}","commit":{"hash":"${{ github.sha }}","message":"${{ github.event.head_commit.message }}","url":"https://github.com/${{ github.event.organization }}/${{ github.repository }}/commit/${{ github.sha }}"},"workflow":"${{ github.workflow }}","status":"${{ needs.build.result }}", "buildId": "${{ github.run_id }}", "timestamp": "'"$TIMESTAMP"'", "duration": "${{ needs.build.outputs.duration }}"}' \
          ${{ env.API_URL }}/notifications
