name: Email API CI Build

run-name: Build triggered by ${{ github.event_name }} & defined by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Build project'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: yarn --frozen-lockfile && du -sh ./node_modules
    - run: yarn build && du -sh ./dist